spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.75.130:3316/dadal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      db-type: mysql
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 60000   #获取连接等待时间60秒,超时将会报错
      validation-query: SELECT 3  #验证连接有效性
      test-while-idle: true   #空闲时校验是否有效
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000  #每60秒执行一次连接回收器
      min-evictable-idle-time-millis: 600000    #10分钟内没有任何操作的空闲连接会被回收
      filters: stat  #设置过滤器，stat用于接收状态，wall用于防止SQL注入,logback则说明使用logback日志输出
      use-global-data-source-stat: true   #统计所有数据源状态
      filter:
        stat:
          merge-sql: true   #合并统计sql
          slow-sql-millis: 300   #慢查询过滤定义

  #html templates config
  mvc:
    view:
      prefix: /
      suffix: .html
  #set cache manager type
  cache:
    type: redis
  #redis
  redis:
    database: 5
    #办公本CentOS7 Linux redis服务地址
    host: 192.168.75.130
    #便携本Windows 本地redis服务地址
    #host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 20000
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
  #spring data elasticsearch config
  elasticsearch:
    rest:
      uris: 192.168.75.130:9201, 192.168.75.130:9202, 192.168.75.130:9203
      connection-timeout: 60
      read-timeout: 60
      username: elastic
      password: 123456

#register-url
#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://register-center-1001:1001/eureka/

#logging configs
logging:
  config: classpath:logback-spring.xml

#mybatis configs location
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:/mybatis-config.xml

app:
  version: v2.0

#limited of data query
limited:
  count: 1_00

config:
  upload:
    filepath: D:\demo\upload
  ftp:
    url: 192.168.75.130
    port: 9009
    username: frank
    password: 123456
    filedir: /home/dadal/upload/file
    encode: GBK						    # ftp服务内文件的编码格式
    isRunner: true					    # 是否开启连接ftp，true为当前服务器ftp下载文件，false为不连接ftp
    mode: pasv						    # port是主动模式,pasv是被动模式
    cron: 0 0 0 * * ?					# ftp扫描时间表达式
    retryCount: 3						# 重连次数

ai:
  appId: 15191935
  apiKey: cyWSHgas93Vtdmt42OwbW8pu
  secretKey: yf1GusMvvLBdOnyubfLubNyod9iEDEZW
  imageType: BASE64
  groupId: itcast
qr:
  url: https://192.168.75.130:8888/#/facelogin