#port
server:
    port: 55555

spring:
    #application name
    application:
        name: dadal-cloud-branch
        
    #MySQL
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dadal?serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: root
        
    #html templates config
    mvc:
        view:
            prefix: /
            suffix: .html

#register-url
#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://register-center-1001:1001/eureka/

#logging configs
logging:
    config: classpath:logback-spring.xml
  
#mapper files location
mybatis:
    mapper-locations: classpath:mapper/**/*.xml